export const data1 = [
	{ College: "HKCC", gpa: 3.2, uni: "CUHK" , comment: "comment1comment1comment1comment1comment1", uniprog: "Artificial Intelligence", ccprog: "Information Technology"},
	{ College: "SPACE", gpa: 3.5, uni: "CUHK", comment: "comment2", uniprog: "Artificial Intelligence", ccprog: "Computer Engineering"},
	{ College: "HKCC", gpa: 3.0, uni: "CUHK" , comment: "comment3", uniprog: "Artificial Intelligence", ccprog: "Information Technology"},
	{ College: "IVE", gpa: 3.3, uni: "CUHK" , comment: "comment4", uniprog: "Artificial Intelligence", ccprog: "Software Engineering"},
	{ College: "Other", gpa: 3.3, uni: "CUHK" , comment: "comment5", uniprog: "Artificial Intelligence", ccprog: "Information Technology"},
	{ College: "HKCC", gpa: 3.8, uni: "CUHK" , comment: "comment6", uniprog: "Artificial Intelligence", ccprog: "Information Technology"},
	{ College: "Other", gpa: 4, uni: "CUHK", comment: "comment7", uniprog: "Artificial Intelligence", ccprog: "Information Technology"},
	{ College: "SPACE", gpa: 3.5, uni: "CUHK", comment: "comment8", uniprog: "Artificial Intelligence", ccprog: "Computer Engineering" },
	{ College: "HKCC", gpa: 3.8, uni: "CUHK", comment: "comment9", uniprog: "Artificial Intelligence", ccprog: "Information Technology"},
	{ College: "IVE", gpa: 3.7, uni: "CUHK", comment: "comment10", uniprog: "Artificial Intelligence", ccprog: "Software Engineering" },
	{ College: "Other", gpa: 3.6, uni: "CUHK", comment: "comment11", uniprog: "Artificial Intelligence", ccprog: "Information Technology"},
	{ College: "HKCC", gpa: 3.99, uni: "CUHK", comment: "comment12", uniprog: "Artificial Intelligence", ccprog: "Information Technology"},
	{ College: "SPACE", gpa: 4, uni: "CUHK", comment: "comment13", uniprog: "Artificial Intelligence", ccprog: "Computer Engineering"},
	{ College: "SPACE", gpa: 3.95, uni: "CUHK", comment: "comment14", uniprog: "Artificial Intelligence", ccprog: "Computer Engineering" },
	{ College: "HKCC", gpa: 3.88, uni: "CUHK", comment: "comment15", uniprog: "Artificial Intelligence", ccprog: "Information Technology"},
	{ College: "IVE", gpa: 3.98, uni: "CUHK", comment: "comment15", uniprog: "Artificial Intelligence", ccprog: "Software Engineering"},
	{ College: "Other", gpa: 3.5, uni: "CUHK", comment: "comment16", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },
	{ College: "HKCC", gpa: 3.77, uni: "CUHK", comment: "comment17", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },
];
