export const data1 = [
    { id: "1", College: "HKCC", gpa: 3.2, uni: "CUHK", comment: "comment1comment1comment1comment1comment1", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },
    { id: "1", College: "SPACE", gpa: 3.5, uni: "CUHK", comment: "comment2", uniprog: "Artificial Intelligence", ccprog: "Computer Engineering" },
    { id: "1", College: "HKCC", gpa: 3.0, uni: "CUHK", comment: "comment3", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },
    { id: "1", College: "IVE", gpa: 3.3, uni: "CUHK", comment: "comment4", uniprog: "Artificial Intelligence", ccprog: "Software Engineering" },
    { id: "1", College: "Other", gpa: 3.3, uni: "CUHK", comment: "comment5", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },
    { id: "1", College: "HKCC", gpa: 3.8, uni: "CUHK", comment: "comment6", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },
    { id: "1", College: "Other", gpa: 4, uni: "CUHK", comment: "comment7", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },
    { id: "1", College: "SPACE", gpa: 3.5, uni: "CUHK", comment: "comment8", uniprog: "Artificial Intelligence", ccprog: "Computer Engineering" },
    { id: "1", College: "HKCC", gpa: 3.8, uni: "CUHK", comment: "comment9", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },
    { id: "1", College: "IVE", gpa: 3.7, uni: "CUHK", comment: "comment10", uniprog: "Artificial Intelligence", ccprog: "Software Engineering" },
    { id: "1", College: "Other", gpa: 3.6, uni: "CUHK", comment: "comment11", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },
    { id: "1", College: "HKCC", gpa: 3.99, uni: "CUHK", comment: "comment12", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },
    { id: "1", College: "SPACE", gpa: 4, uni: "CUHK", comment: "comment13", uniprog: "Artificial Intelligence", ccprog: "Computer Engineering" },
    { id: "1", College: "SPACE", gpa: 3.95, uni: "CUHK", comment: "comment14", uniprog: "Artificial Intelligence", ccprog: "Computer Engineering" },
    { id: "1", College: "HKCC", gpa: 3.88, uni: "CUHK", comment: "comment15", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },
    { id: "1", College: "IVE", gpa: 3.98, uni: "CUHK", comment: "comment15", uniprog: "Artificial Intelligence", ccprog: "Software Engineering" },
    { id: "1", College: "Other", gpa: 3.5, uni: "CUHK", comment: "comment16", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },
    { id: "1", College: "HKCC", gpa: 3.77, uni: "CUHK", comment: "comment17", uniprog: "Artificial Intelligence", ccprog: "Information Technology" },

    { id: "2", College: "HKCC", gpa: 3.3, uni: "CUHK", comment: "comment1comment1comment1comment1comment18", uniprog: "Computer Engineering", ccprog: "Information Technology" },
    { id: "2", College: "SPACE", gpa: 3.4, uni: "CUHK", comment: "comment19", uniprog: "Computer Engineering", ccprog: "Computer Engineering" },
    { id: "2", College: "HKCC", gpa: 3.2, uni: "CUHK", comment: "comment20", uniprog: "Computer Engineering", ccprog: "Information Technology" },
    { id: "2", College: "IVE", gpa: 3.1, uni: "CUHK", comment: "comment21", uniprog: "Computer Engineering", ccprog: "Software Engineering" },
    { id: "2", College: "Other", gpa: 3.6, uni: "CUHK", comment: "comment22", uniprog: "Computer Engineering", ccprog: "Information Technology" },
    { id: "2", College: "HKCC", gpa: 3.37, uni: "CUHK", comment: "comment23", uniprog: "Computer Engineering", ccprog: "Information Technology" },
    { id: "2", College: "Other", gpa: 3.44, uni: "CUHK", comment: "comment24", uniprog: "Computer Engineering", ccprog: "Information Technology" },
    { id: "2", College: "SPACE", gpa: 3.55, uni: "CUHK", comment: "comment25", uniprog: "Computer Engineering", ccprog: "Computer Engineering" },
    { id: "2", College: "HKCC", gpa: 3.73, uni: "CUHK", comment: "comment26", uniprog: "Computer Engineering", ccprog: "Information Technology" },
    { id: "2", College: "IVE", gpa: 3.88, uni: "CUHK", comment: "comment27", uniprog: "Computer Engineering", ccprog: "Software Engineering" },
    { id: "2", College: "Other", gpa: 3.61, uni: "CUHK", comment: "comment28", uniprog: "Computer Engineering", ccprog: "Information Technology" },
    { id: "2", College: "HKCC", gpa: 3.23, uni: "CUHK", comment: "comment29", uniprog: "Computer Engineering", ccprog: "Information Technology" },
    { id: "2", College: "SPACE", gpa: 4, uni: "CUHK", comment: "comment30", uniprog: "Computer Engineering", ccprog: "Computer Engineering" },
    { College: "SPACE", gpa: 3.39, uni: "CUHK", comment: "comment31", uniprog: "Computer Engineering", ccprog: "Computer Engineering" },
    { id: "2", College: "HKCC", gpa: 3.41, uni: "CUHK", comment: "comment32", uniprog: "Computer Engineering", ccprog: "Information Technology" },
    { id: "2", College: "IVE", gpa: 3.27, uni: "CUHK", comment: "comment33", uniprog: "Computer Engineering", ccprog: "Software Engineering" },
    { id: "2", College: "Other", gpa: 3.99, uni: "CUHK", comment: "comment34", uniprog: "Computer Engineering", ccprog: "Information Technology" },
    { id: "2", College: "HKCC", gpa: 3.87, uni: "CUHK", comment: "comment35", uniprog: "Computer Engineering", ccprog: "Information Technology" },

    { id: "3", College: "HKCC", gpa: 3.3, uni: "CUHK", comment: "comment1comment1comment1comment1comment18", uniprog: "Computer Science", ccprog: "Information Technology" },
    { id: "3", College: "SPACE", gpa: 3.1, uni: "CUHK", comment: "comment36", uniprog: "Computer Science", ccprog: "Computer Engineering" },
    { id: "3", College: "HKCC", gpa: 3.12, uni: "CUHK", comment: "comment37", uniprog: "Computer Science", ccprog: "Information Technology" },
    { id: "3", College: "IVE", gpa: 3.1, uni: "CUHK", comment: "comment38", uniprog: "Computer Science", ccprog: "Software Engineering" },
    { id: "3", College: "Other", gpa: 3.32, uni: "CUHK", comment: "comment39", uniprog: "Computer Science", ccprog: "Information Technology" },
    { id: "3", College: "HKCC", gpa: 3.44, uni: "CUHK", comment: "comment40", uniprog: "Computer Science", ccprog: "Information Technology" },
    { id: "3", College: "Other", gpa: 3.05, uni: "CUHK", comment: "comment41", uniprog: "Computer Science", ccprog: "Information Technology" },
    { id: "3", College: "SPACE", gpa: 3.01, uni: "CUHK", comment: "comment42", uniprog: "Computer Science", ccprog: "Computer Engineering" },
    { id: "3", College: "HKCC", gpa: 3.09, uni: "CUHK", comment: "comment43", uniprog: "Computer Science", ccprog: "Information Technology" },
    { id: "3", College: "IVE", gpa: 3.29, uni: "CUHK", comment: "comment44", uniprog: "Computer Science", ccprog: "Software Engineering" },
    { id: "3", College: "Other", gpa: 3.14, uni: "CUHK", comment: "comment28", uniprog: "Computer Science", ccprog: "Information Technology" },
    { id: "3", College: "HKCC", gpa: 3.29, uni: "CUHK", comment: "comment29", uniprog: "Computer Science", ccprog: "Information Technology" },
    { id: "3", College: "SPACE", gpa: 3.4, uni: "CUHK", comment: "comment30", uniprog: "Computer Science", ccprog: "Computer Engineering" },
    { College: "SPACE", gpa: 3.33, uni: "CUHK", comment: "comment31", uniprog: "Computer Science", ccprog: "Computer Engineering" },
    { id: "3", College: "HKCC", gpa: 3.28, uni: "CUHK", comment: "comment32", uniprog: "Computer Science", ccprog: "Information Technology" },
    { id: "3", College: "IVE", gpa: 3.27, uni: "CUHK", comment: "comment33", uniprog: "Computer Science", ccprog: "Software Engineering" },
    { id: "3", College: "Other", gpa: 3.13, uni: "CUHK", comment: "comment34", uniprog: "Computer Science", ccprog: "Information Technology" },
    { id: "3", College: "HKCC", gpa: 3.03, uni: "CUHK", comment: "comment35", uniprog: "Computer Science", ccprog: "Information Technology" },
];
